name: Vouch

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issues:
    types: [opened, reopened]

jobs:
  check-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: mitchellh/vouch/action/check-pr@v1

  check-issue:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: mitchellh/vouch/action/check-issue@v1
